### ISSUE TITLE
Failure to find rails version causes an error

### ISSUE THREAD

**Issue by xxChinasaurxx** [RIDEeditor/ride#5]
If 'rails' cannot be found on the path, then the .match() call in [rails_ui.js](https://github.com/RIDEeditor/ride/blob/32b92aef2e651fd775987efa81898b64c6009d0b/js/rails_ui/rails_ui.js#L20) fails to extract a version string and trying to index the value 1 gives: 'Uncaught TypeError: Cannot read property '1' of null'

**Comment by arrayoutofbounds** [comment]
I have made a change so that it does not occur. Please test again
